---
ansible_python_interpreter: /usr/bin/python3

# env
cluster_name: "{{ lookup('env', 'CLUSTER_NAME') }}"
app_cluster_ip: "{{ lookup('env', 'APP_CLUSTER_IP') }}"
db_cluster_ip: "{{ lookup('env', 'DB_CLUSTER_IP') }}"
kibana_cluster_ip: "{{ lookup('env', 'KIBANA_CLUSTER_IP') }}"

# nginx
nginx_port: 8000
nginx_user: www-data

# elasticsearch
elasticsearch_host: 127.0.0.1
elasticsearch_port: 9200

# logstash
logstash_host: 127.0.0.1
logstash_beats_port: 5044
logstash_gelf_port: 12201
logstash_tcp_port: 4000

# kibana
kibana_host: 127.0.0.1
kibana_port: 5601

# postgresql
postgresql_host: 0.0.0.0
postgresql_port: 5432

# redis
redis_host: 0.0.0.0
redis_port: 6379
redis_db: 0

# solr
solr_host: 0.0.0.0
solr_port: 8983
solr_core: app

# puma
puma_sock: /tmp/puma.sock

# app
app_path: /var/www/app
