---
ansible_python_interpreter: /usr/bin/python3

# nginx
nginx_port: 8000
nginx_user: www-data

# app server
app_server_host: 0.0.0.0
app_server_port: 80
app_server_path: /hls

# backup server
backup_server_host: link12.ddns.net
backup_server_port: 8080
backup_server_path: /Volumes/Untitled

# elasticsearch
elasticsearch_host: 127.0.0.1
elasticsearch_port: 9200

# logstash
logstash_host: 127.0.0.1
logstash_beats_port: 5044
logstash_gelf_port: 12201
logstash_tcp_port: 4000
logstash_host_remote: "{{ lookup('env', 'KIBANA_IP') }}"

# kibana
kibana_host: 127.0.0.1
kibana_port: 5601

# postgresql
postgresql_host: 0.0.0.0
postgresql_port: 5432

# redis
redis_host: 0.0.0.0
redis_port: 6379
redis_db: 0

# solr
solr_core: app
solr_host: 0.0.0.0
solr_port: 8983

# puma
puma_sock: /tmp/puma.sock

# app
app_path: /var/www/app
