---
ansible_python_interpreter: /usr/bin/python3

# host
host_dns_server: 192.168.1.1

# docker network
docker_network_subnet: 172.28.0.0/16
docker_network_gateway: 172.28.5.254
docker_network_iprange: 172.28.5.0/24

# docker debian-stretch
docker_stretch_home_ipv4_address: 172.28.5.0
docker_stretch_external_ssh_port: 2201
docker_stretch_external_http_port: 8001

# docker debian-sid
docker_sid_home_ipv4_address: 172.28.5.1
docker_sid_external_ssh_port: 2200
docker_sid_external_http_port: 8000

# elasticsearch
elasticsearch_host: 127.0.0.1
elasticsearch_port: 9200

# logstash
logstash_gelf_port: 12201
logstash_beats_port: 5044
logstash_tcp_port: 4000

# kibana
kibana_host: 127.0.0.1
kibana_port: 5601

# postgresql
postgresql_host: 127.0.0.1
postgresql_port: 5432

# redis
redis_host: 127.0.0.1
redis_port: 6379
redis_db: 0

# solr
solr_host: 127.0.0.1
solr_port: 8983
solr_core: app

# nginx
nginx_port: 80

# puma
puma_sock: /tmp/puma.sock
