---
- name: Install postgresql-13
  tags: postgresql
  apt:
    name:
      - postgresql-13
  no_log: True

- name: Install postgresql dependencies
  tags: postgresql
  apt:
    name:
      - libpq-dev
  no_log: True

- name: Include vault pg vars
  tags: postgresql
  include_vars:
    file: vault_pg.yml
  no_log: True

- name: Configure postgresql
  tags: postgresql
  template:
    src: postgresql.conf.j2
    dest: "{{ postgresql_conf }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_user }}"
    mode: 0644
  no_log: True

- name: Add 0.0.0.0/32 to pg hba file
  tags: postgresql
  become_user: "{{ postgresql_user }}"
  community.general.postgresql_pg_hba:
    dest: "{{ postgresql_pg_hba_file }}"
    contype: host
    users: all
    databases: all
    source: "0.0.0.0/32"
    method: trust
    create: true
  no_log: True

- name: Add 10.0.0.1/32 to pg hba file
  tags: postgresql
  become_user: "{{ postgresql_user }}"
  community.general.postgresql_pg_hba:
    dest: "{{ postgresql_pg_hba_file }}"
    contype: host
    users: all
    databases: all
    source: "10.0.0.1/32"
    method: trust
    create: true
  no_log: True

- name: Start postgresql
  tags: postgresql
  systemd:
    daemon_reload: True
    state: started
    name: postgresql

- name: Set postgresql user credentials
  tags: postgresql
  become_user: "{{ postgresql_user }}"
  community.general.postgresql_user:
    name: "{{ postgresql_username }}"
    password: "{{ postgresql_password }}"
  no_log: True

- name: Create postgresql database
  tags: postgresql
  become_user: "{{ postgresql_user }}"
  community.general.postgresql_db:
    name: "{{ postgresql_database }}"
    login_user: "{{ postgresql_username }}"
    login_password: "{{ postgresql_password }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
  no_log: True
