---
- name: Install PostgreSQL
  apt:
    name: postgresql-12

- name: Configure PostgreSQL
  command: "echo \"host all all 0.0.0.0/0 trust\" >> /etc/postgresql/12/main/pg_hba.conf"

- name: systemd daemon_reload
  systemd:
    daemon_reload: yes

- name: systemd daemon_reexec
  systemd:
    daemon_reexec: yes

- name: Start postgresql
  systemd:
    state: started
    name: postgresql
