---
- name: Install postgresql-12
  apt:
    name: postgresql-12

- name: Configure postgresql
  community.general.postgresql_pg_hba:
    dest: "{{ pg_hba_dest }}"
    contype: host
    users: all
    databases: all
    source: "{{ pg_hba_source }}"
    method: trust
    create: true

- name: systemd daemon_reload
  systemd:
    daemon_reload: yes

- name: systemd daemon_reexec
  systemd:
    daemon_reexec: yes

- name: Start postgresql
  systemd:
    state: started
    name: postgresql

- name: Set postgres user password
  become_user: postgres
  community.general.postgresql_user:
    name: "{{ pg_login_user }}"
    password: "{{ pg_login_password }}"
