---
- name: Install postgresql-12
  apt:
    name: postgresql-12

- name: Configure postgresql
  command: "echo \"host all all {{ pg_host }}/0 trust\" >> {{ pg_hba_path }}"

- name: systemd daemon_reload
  systemd:
    daemon_reload: yes

- name: systemd daemon_reexec
  systemd:
    daemon_reexec: yes

- name: Start postgresql
  systemd:
    state: started
    name: postgresql
