---
- name: Install postgresql-12
  apt:
    name: postgresql-12

- name: Configure postgresql
  community.general.postgresql_pg_hba:
    dest: "{{ pg_hba_dest }}"
    contype: host
    users: all
    databases: all
    source: "{{ pg_hba_source }}"
    method: trust
    create: true

- name: Start postgresql
  systemd:
    daemon_reload: True
    state: started
    name: postgresql
