---
- name: Install redis-server
  apt:
    name: redis-server

- name: Configure redis
  template:
    src: redis.conf.j2
    dest: "{{ redis_config_file }}"
    mode: 0644

- name: systemd daemon_reload
  systemd:
    daemon_reload: yes

- name: systemd daemon_reexec
  systemd:
    daemon_reexec: yes

- name: Start redis
  systemd:
    state: started
    name: redis
