---
- name: Install redis-server
  tags: redis
  apt:
    name: redis-server
  no_log: True

- name: Configure redis
  tags: redis
  template:
    src: redis.conf.j2
    dest: "{{ redis_config_file }}"
    mode: 0644
  no_log: True

- name: Start redis
  tags: redis
  service:
    state: started
    name: redis-server
    enabled: True
