---
- name: Install logstash
  tags: logstash
  apt:
    name:
      - logstash
  no_log: True

- name: Configure logstash
  tags: logstash
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  loop:
    - { src: logstash.conf.j2,  dest: "{{ logstash_config_path }}" }
    - { src: logstash_patterns, dest: "{{ logstash_patterns_path }}" }
  no_log: True

- name: Logstash system-install
  tags: logstash
  command: /usr/share/logstash/bin/system-install /etc/logstash/startup.options sysv
  no_log: True

- name: Start logstash
  tags: logstash
  service:
    state: started
    name: logstash
    enabled: True
