---
- name: Install nginx
  tags: nginx
  apt:
    name: nginx
  no_log: True

- name: Configure nginx {{ docker_stretch_home_hostname }}
  tags: nginx
  when: inventory_hostname == "{{ docker_stretch_home_hostname }}"
  template:
    src: "nginx.{{ docker_stretch_home_hostname }}.conf.j2"
    dest: "{{ nginx_config_path }}"
    mode: 0644
  no_log: True

- name: Configure nginx {{ docker_sid_home_hostname }}
  tags: nginx
  when: inventory_hostname == "{{ docker_sid_home_hostname }}"
  template:
    src: "nginx.{{ docker_sid_home_hostname }}.conf.j2"
    dest: "{{ nginx_config_path }}"
    mode: 0644
  no_log: True

- name: Start nginx
  tags: nginx
  systemd:
    daemon_reload: True
    state: started
    name: nginx
  no_log: True
