---
- name: Install nginx
  apt:
    name: nginx

- name: Configure nginx
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_config_path }}"
    mode: 0644

- name: Start nginx
  systemd:
    daemon_reload: True
    state: started
    name: nginx
