---
- name: Install nginx
  apt:
    name: nginx

- name: Configure nginx
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_config_path }}"
    mode: 0644

- name: systemd daemon_reload
  systemd:
    daemon_reload: yes

- name: systemd daemon_reexec
  systemd:
    daemon_reexec: yes

- name: Start nginx
  systemd:
    state: started
    name: nginx
