---
- name: Install nginx
  tags: nginx
  apt:
    name: nginx

- name: Include nginx vault vars
  include_vars:
    file: vault_nginx.yml
  no_log: True

- name: Copy nginx server cert
  copy:
    content: "{{ nginx_server_crt }}"
    dest: "{{ nginx_cert_path }}"
    mode: 0644
    owner: "{{ ansible_user }}"
  no_log: True

- name: Copy nginx server key
  copy:
    content: "{{ nginx_server_key }}"
    dest: "{{ nginx_key_path }}"
    mode: 0644
    owner: "{{ ansible_user }}"
  no_log: True

- name: Copy nginx dhparam pem
  copy:
    content: "{{ dhparam_pem }}"
    dest: "{{ nginx_dhparam_pem_path }}"
    mode: 0644
    owner: "{{ ansible_user }}"
  no_log: True

- name: Create nginx ssl config file
  template:
    src: ssl.conf.j2
    dest: "{{ nginx_ssl_etc_path }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: 0644

- name: Create nginx ssl-params config file
  template:
    src: ssl-params.conf.j2
    dest: "{{ nginx_ssl_params_etc_path }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: 0644

- name: Configure nginx
  tags: nginx
  template:
    src: "nginx.conf.j2"
    dest: "{{ nginx_config_path }}"
    mode: 0644

- name: Add nginx config to sites-enabled
  tags: nginx
  template:
    src: "nginx-app.conf.j2"
    dest: "{{ nginx_sites_enabled_path }}/frontend"
    mode: 0644

- name: Remove default site from sites-enabled
  file:
    path: "{{ nginx_sites_enabled_path }}/default"
    state: absent

- name: Start nginx
  tags: nginx
  systemd:
    daemon_reload: True
    state: started
    name: nginx
