---
- name: Install nginx
  apt:
    name: nginx

- name: Configure nginx for elasticsearch / kibana
  when: inventory_hostname == "stretch.home"
  template:
    src: nginx-elk.conf.j2
    dest: "{{ nginx_config_path }}"
    mode: 0644

- name: Configure nginx for application
  when: inventory_hostname == "sid.home"
  template:
    src: nginx-app.conf.j2
    dest: "{{ nginx_config_path }}"
    mode: 0644

- name: Start nginx
  systemd:
    daemon_reload: True
    state: started
    name: nginx
