---
- name: Install rsyslog
  apt:
    name:
      - rsyslog

- name: Configure rsyslog
  lineinfile:
    line: "*.* @@{{ logstash_host }}:{{ logstash_tcp_port }}"
    dest: "{{ rsyslog_config_path }}"
    create: True

- name: Start rsyslog
  systemd:
    daemon_reload: True
    state: started
    name: rsyslog
