---
- name: Install rsyslog
  tags: rsyslog
  apt:
    name:
      - rsyslog
  no_log: True

- name: Start rsyslog
  tags: rsyslog
  systemd:
    daemon_reload: True
    state: started
    name: rsyslog
