---
# git
- name: Add github to known_hosts
  tags: admin
  lineinfile:
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    dest: "/root/.ssh/known_hosts"
    mode: 0644
    owner: root
    create: True

- name: Checkout admin repository
  tags: admin
  git:
    repo: "{{ admin_repository }}"
    dest: "{{ admin_path }}"
    version: dev

# namespace
- name: Create development namespace
  tags: admin
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl apply -f namespace/development.yaml

# prometheus-community charts
- name: Add prometheus-community repository
  tags: admin prometheus
  shell:
    chdir: "{{ admin_path }}"
    cmd: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

# prometheus
- name: Install prometheus
  tags: admin prometheus
  shell:
    chdir: "{{ admin_path }}"
    cmd: helm upgrade --install -f helm/prometheus.yaml prometheus prometheus-community/prometheus --namespace development

- name: Set prometheus service external IP
  tags: admin prometheus
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n development patch svc prometheus-server -p '{"spec":{"externalIPs":["{{ apiserver_advertise_address }}"]}}'

# node-exporter
- name: Install node-exporter
  tags: admin prometheus node-exporter
  shell:
    chdir: "{{ admin_path }}"
    cmd: helm upgrade --install -f helm/node-exporter.yaml node-exporter prometheus-community/prometheus-node-exporter --namespace development

# postgresql
- name: Include vault postgresql
  tags: postgresql
  include_vars: env_vault_postgresql.yaml
  # no_log: True

- name: Check for previous deployments of postgresql
  tags: admin postgresql
  register: postgresqldeployment
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n development get statefulsets -o json | jq -r '.items[].spec.template.spec.containers[].name' | grep ^postgresql || true

- name: Create postgresql configmap
  tags: admin postgresql
  shell:
    cmd: |
      cat <<EOF | kubectl apply -f -
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: postgresql-env
          namespace: development
          labels:
            app: postgresql
        data:
          POSTGRES_DB: {{ postgres_db }}
          POSTGRES_USER: {{ postgres_user }}
          POSTGRES_PASSWORD: {{ postgres_password }}
      EOF
  when: postgresqldeployment.stdout == ""

- name: Create postgresql persistent volume
  tags: admin postgresql
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n development apply -f storage/persistent-volume.yaml
  when: postgresqldeployment.stdout == ""

- name: Create postgresql persistent volume claim
  tags: admin postgresql
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n development apply -f storage/persistent-volume-claim.yaml
  when: postgresqldeployment.stdout == ""

- name: Create postgresql deployment
  tags: admin postgresql
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n development replace --force -f statefulset/postgresql.yaml
  when: postgresqldeployment.stdout == ""

- name: Create postgresql loadbalancer
  tags: admin postgresql
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n development replace --force -f service/postgresql.yaml
  when: postgresqldeployment.stdout == ""

- name: Set postgresql service external IP
  tags: admin postgresql
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n development patch svc postgresql-svc -p '{"spec":{"externalIPs":["{{ apiserver_advertise_address }}"]}}'
  when: postgresqldeployment.stdout == ""

# prometheus-postgres-exporter
- name: Install prometheus-postgres-exporter
  tags: admin prometheus
  shell:
    chdir: "{{ admin_path }}"
    cmd: helm upgrade --install -f helm/prometheus-postgres-exporter.yaml prometheus-postgres-exporter prometheus-community/prometheus-postgres-exporter --namespace development

- name: Set prometheus-postgres-exporter service external IP
  tags: admin prometheus
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n development patch svc prometheus-postgres-exporter -p '{"spec":{"externalIPs":["{{ apiserver_advertise_address }}"]}}'

# redis
- name: Check for previous deployments of redis
  tags: admin redis
  register: redisdeployment
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n development get statefulset -o json | jq -r '.items[].spec.template.spec.containers[].name' | grep ^redis || true

- name: Create redis deployment
  tags: admin redis
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n development replace --force -f statefulset/redis.yaml
  when: redisdeployment.stdout == ""

- name: Create redis loadbalancer
  tags: admin redis
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n development replace --force -f service/redis.yaml
  when: redisdeployment.stdout == ""

- name: Set redis service external IP
  tags: admin redis
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n development patch svc redis-loadbalancer -p '{"spec":{"externalIPs":["{{ apiserver_advertise_address }}"]}}'
  when: redisdeployment.stdout == ""

# prometheus-redis-exporter
- name: Install prometheus-redis-exporter
  tags: admin prometheus
  shell:
    chdir: "{{ admin_path }}"
    cmd: helm upgrade --install -f helm/prometheus-redis-exporter.yaml prometheus-redis-exporter prometheus-community/prometheus-redis-exporter --namespace development

- name: Set prometheus-redis-exporter service external IP
  tags: admin prometheus
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n development patch svc prometheus-redis-exporter -p '{"spec":{"externalIPs":["{{ apiserver_advertise_address }}"]}}'

# app-backend
- name: Include vault
  tags: app-backend
  include_vars: env_vault_backend.yaml

- name: Create environment temporary configuration file
  tags: admin app-backend
  template:
    src: app-backend.env.j2
    dest: /tmp/.env
    owner: root
    group: root
    mode: 0644
  no_log: True

- name: Create environment secret
  tags: admin app-backend
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl create secret generic app-backend-env --namespace=development --from-file=/tmp/.env --dry-run=client -o yaml | kubectl -n development replace --force -f -

- name: Remove environment temporary configuration file
  tags: admin app-backend
  ansible.builtin.file:
    path: /tmp/.env
    state: absent
  no_log: True

- name: Create app-backend deployment
  tags: admin app-backend
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n development replace --force -f deploy/app-backend.yaml

- name: Create app-backend loadbalancer
  tags: admin app-backend
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n development replace --force -f service/app-backend.yaml

- name: Set app-backend service external IP
  tags: admin app-backend
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n development patch svc app-backend-loadbalancer -p '{"spec":{"externalIPs":["{{ apiserver_advertise_address }}"]}}'

# nginx-backend
- name: Create nginx-backend deployment
  tags: admin nginx-backend
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n development replace --force -f deploy/nginx-backend.yaml

- name: Create nginx-backend loadbalancer
  tags: admin nginx-backend
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n development replace --force -f service/nginx-backend.yaml

- name: Set nginx-backend service external IP
  tags: admin nginx-backend
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n development patch svc nginx-backend-loadbalancer -p '{"spec":{"externalIPs":["{{ apiserver_advertise_address }}"]}}'

# prometheus-nginx-exporter backend
- name: Install prometheus-nginx-exporter backend
  tags: admin prometheus nginx-backend
  shell:
    chdir: "{{ admin_path }}"
    cmd: helm upgrade --install -f helm/prometheus-nginx-exporter-backend.yaml prometheus-nginx-exporter-backend prometheus-community/prometheus-nginx-exporter --namespace development

- name: Set prometheus-nginx-exporter backend service external IP
  tags: admin prometheus nginx-backend
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n development patch svc prometheus-nginx-exporter-backend -p '{"spec":{"externalIPs":["{{ apiserver_advertise_address }}"]}}'

# app-stream
- name: Include vault
  tags: app-stream
  include_vars: env_vault_stream.yaml

- name: Create environment temporary configuration file
  tags: admin app-stream
  template:
    src: app-stream.env.j2
    dest: /tmp/.env
    owner: root
    group: root
    mode: 0644
  no_log: True

- name: Create environment secret
  tags: admin app-stream
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl create secret generic app-stream-env --namespace=development --from-file=/tmp/.env --dry-run=client -o yaml | kubectl -n development replace --force -f -

- name: Remove environment temporary configuration file
  tags: admin app-stream
  ansible.builtin.file:
    path: /tmp/.env
    state: absent
  no_log: True

- name: Create app-stream deployment
  tags: admin app-stream
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n development replace --force -f deploy/app-stream.yaml

- name: Create app-stream loadbalancer
  tags: admin app-stream
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n development replace --force -f service/app-stream.yaml

- name: Set app-stream service external IP
  tags: admin app-stream
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n development patch svc app-stream-loadbalancer -p '{"spec":{"externalIPs":["{{ apiserver_advertise_address }}"]}}'

# nginx-stream
- name: Create nginx-stream Deployment
  tags: admin nginx-stream
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n development replace --force -f deploy/nginx-stream.yaml

- name: Create nginx-stream loadbalancer
  tags: admin nginx-stream
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n development replace --force -f service/nginx-stream.yaml

- name: Set nginx-stream service external IP
  tags: admin nginx-stream
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n development patch svc nginx-stream-loadbalancer -p '{"spec":{"externalIPs":["{{ apiserver_advertise_address }}"]}}'

# prometheus-nginx-exporter stream
- name: Install prometheus-nginx-exporter stream
  tags: admin prometheus nginx-stream
  shell:
    chdir: "{{ admin_path }}"
    cmd: helm upgrade --install -f helm/prometheus-nginx-exporter-stream.yaml prometheus-nginx-exporter-stream prometheus-community/prometheus-nginx-exporter --namespace development

- name: Set nginx-stream service external IP
  tags: admin prometheus nginx-stream
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n development patch svc prometheus-nginx-exporter-stream -p '{"spec":{"externalIPs":["{{ apiserver_advertise_address }}"]}}'

# nginx-frontend
- name: Create nginx-frontend Deployment
  tags: admin nginx-frontend
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n development replace --force -f deploy/nginx-frontend.yaml

- name: Create nginx-frontend loadbalancer
  tags: admin nginx-frontend
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n development replace --force -f service/nginx-frontend.yaml

- name: Set nginx-frontend service external IP
  tags: admin nginx-frontend
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n development patch svc nginx-frontend-loadbalancer -p '{"spec":{"externalIPs":["{{ apiserver_advertise_address }}"]}}'

# prometheus-nginx-exporter frontend
- name: Install prometheus-nginx-exporter frontend
  tags: admin prometheus nginx-frontend
  shell:
    chdir: "{{ admin_path }}"
    cmd: helm upgrade --install -f helm/prometheus-nginx-exporter-frontend.yaml prometheus-nginx-exporter-frontend prometheus-community/prometheus-nginx-exporter --namespace development

- name: Set prometheus-nginx-exporter-frontend service external IP
  tags: admin prometheus nginx-frontend
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n development patch svc prometheus-nginx-exporter-frontend -p '{"spec":{"externalIPs":["{{ apiserver_advertise_address }}"]}}'

# grafana
- name: Add grafana repository
  tags: admin grafana
  shell:
    chdir: "{{ admin_path }}"
    cmd: helm repo add grafana https://grafana.github.io/helm-charts

- name: Install grafana
  tags: admin grafana
  shell:
    chdir: "{{ admin_path }}"
    cmd: helm upgrade --install -f helm/grafana.yaml grafana grafana/grafana --namespace development

- name: Set grafana service external IP
  tags: admin grafana
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n development patch svc grafana -p '{"spec":{"externalIPs":["{{ apiserver_advertise_address }}"]}}'

- name: Login to grafana
  tags: admin grafana grafana-login
  register: grafanapasswd  
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl get secret --namespace development grafana -o jsonpath="{.data.admin-password}" | base64 --decode

- name: Debug
  tags: admin grafana grafana-login
  debug:
    var: grafanapasswd

# kubernetes-dashboard
- name: Add kubernetes-dashboard
  tags: admin kubernetes-dashboard
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl apply -f deploy/kubernetes-dashboard.yaml

- name: Set kubernetes-dashboard service external IP
  tags: admin kubernetes-dashboard
  command: kubectl -n kubernetes-dashboard patch svc kubernetes-dashboard -p '{"spec":{"externalIPs":["{{ apiserver_advertise_address }}"]}}'

# kubernetes-dashboard service-account
- name: Setup Service Account Admin User
  tags: admin kubernetes-dashboard
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl apply -f service-account/admin-user.yaml

- name: Setup Service Account Cluster Admin
  tags: admin kubernetes-dashboard
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl apply -f service-account/cluster-admin.yaml

- name: Generate Service Account Token
  tags: admin kubernetes-dashboard
  register: kubernetesdashboardtoken
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n kubernetes-dashboard create token admin-user

- name: Debug
  tags: admin kubernetes-dashboard
  debug:
    var: kubernetesdashboardtoken
