---
- name: Install elasticsearch dependencies
  apt:
    name:
      - wget
      - gnupg
      - openjdk-8-jdk
  no_log: True

- name: Add elastic.co apt key
  apt_key:
    url: "{{ elastic_co_apt_key }}"
    state: present
  no_log: True

- name: Install apt-transport-https
  apt:
    name:
      - apt-transport-https
  no_log: True

- name: Add elastic.co apt repository
  apt_repository:
    repo: deb {{ elastic_co_apt_repository }} stable main
    state: present
    update_cache: true
  no_log: True
