---
- hosts: '*'
  become: True
  gather_facts: False
  roles:
    # base
    - python
    - localtime
    - motd
    - locales
    - vim
    - zsh
    - rsyslog
    - elastic_co
    - filebeat

    # app
    - postgresql
    - redis
    - solr
    - git
    - nginx-app
    - app
