---
- hosts: '*'
  become: True
  gather_facts: False
  roles:
    - python
    - localtime
    - motd
    - locales
    - vim
    - zsh
    - rsyslog-app
    - elastic_co
    - filebeat-app
    - postgresql
    - redis
    - solr
    - git
    - nginx-app
    - app
