---
- hosts: '*'
  become: True
  gather_facts: False
  roles:
    - python
    - localtime
    - motd
    - locales
    - vim
    - zsh
    - rsyslog
    - elastic_co
    - filebeat

- hosts: '*'
  become: True
  gather_facts: False
  tags: deploy
  roles:
    - postgresql
    - redis
    # - solr
