---
- hosts: '*'
  become: True
  gather_facts: False
  roles:
    - apt
    - python
    - localtime
    - motd
    - locales
    - vim
    - zsh
    - rsyslog

- hosts: '*'
  become: True
  gather_facts: False
  tags: deploy
  roles:
    - postgresql
    - redis
