---
- hosts: '*'
  become: True
  gather_facts: False
  roles:
    - python
    - localtime
    - motd
    - locales
    - vim
    - zsh
    - rsyslog-kibana
    - elastic_co
    - filebeat-kibana
    - elasticsearch
    - logstash
    - kibana
    - nginx-kibana
