
- hosts: all
  remote_user: debian
  become: yes
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  
  pre_tasks:
  - name: Install python for Ansible
    become: yes
    raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3-minimal)
    changed_when: False