---
- hosts: localhost
  roles:
    - docker

- hosts: sid.home:stretch.home
  remote_user: debian
  become: True
  gather_facts: False
  roles:
    - python
    - localtime
    - motd
    - locales
    - elasticsearch
    - git
    - vim
    - zsh

- hosts: stretch.home
  remote_user: debian
  become: True
  gather_facts: False
  roles:
    - nginx

- hosts: sid.home
  remote_user: debian
  become: True
  gather_facts: False
  roles:
    - redis
    - postgresql
    - jetty
    - ruby
    - app
