---
  # docker
- hosts: localhost
  roles:
    - docker

  # requirements
- hosts: sid.home:stretch.home
  become: True
  gather_facts: False
  roles:
    - python
    - localtime
    - motd
    - locales
    - git
    - vim
    - zsh
    - elastic_co
    - filebeat
    - rsyslog

  # elasticsearch
- hosts: stretch.home
  become: True
  gather_facts: False
  tags: elasticsearch
  roles:
    - elasticsearch
    - logstash
    - kibana

  # databases
- hosts: sid.home
  become: True
  gather_facts: False
  tags: databases
  roles:
    - postgresql
    - redis
    - solr

  # application
- hosts: sid.home
  become: True
  gather_facts: True
  tags: deploy
  roles:
    - app

  # update solr database
- hosts: sid.home
  become: True
  gather_facts: True
  tags: app_update_solr
  roles:
    - app_update_solr

  # nginx
- hosts: sid.home:stretch.home
  become: True
  gather_facts: False
  tags: nginx
  roles:
    - nginx
