
---
- hosts: localhost
  roles:
    - docker

- hosts: all
  remote_user: debian
  become: yes
  gather_facts: no
  roles:
    - python
    - elasticsearch
    - git

- hosts: sid
  remote_user: debian
  become: yes
  gather_facts: no

  tasks:
    - name: Install ruby-dev
      apt:
        name: ruby-dev

    - name: Install solr-jetty
      apt:
        name: solr-jetty
