---
- hosts: localhost
  roles:
    - docker

- hosts: all
  remote_user: debian
  become: True
  gather_facts: False
  roles:
    - python
    - debian
    - locales
    - elasticsearch
    - git
    - vim

- hosts: sid
  remote_user: debian
  become: True
  gather_facts: False

  tasks:
    - name: Install ruby-dev
      apt:
        name: ruby-dev

    - name: Install solr-jetty
      apt:
        name: solr-jetty
