
---
- hosts: localhost
  roles:
    - docker

- hosts: all
  remote_user: debian
  become: yes
  gather_facts: no
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python3 || (apt install -yq python3)
      changed_when: False

- hosts: all
  remote_user: debian
  become: yes
  gather_facts: no
  roles:
    - elasticsearch
    - git

- hosts: sid
  remote_user: debian
  become: yes
  gather_facts: no

  tasks:
    - name: Install ruby-dev
      apt:
        name: ruby-dev

    - name: Install solr-jetty
      apt:
        name: solr-jetty
