---
  # docker
- hosts: localhost
  roles:
    - docker

  # requirements
- hosts: sid.home:stretch.home
  remote_user: debian
  become: True
  gather_facts: False
  roles:
    - python
    - localtime
    - motd
    - locales
    - git
    - vim
    - zsh
    - elastic_co
    - filebeat
    - rsyslog

  # elasticsearch
- hosts: stretch.home
  remote_user: debian
  become: True
  gather_facts: False
  tags: elasticsearch
  roles:
    - elasticsearch
    - logstash
    - kibana
    - nginx

  # databases, ruby
- hosts: sid.home
  remote_user: debian
  become: True
  gather_facts: False
  roles:
    - redis
    - postgresql
    - jetty
    - ruby

  # application
- hosts: sid.home
  remote_user: debian
  become: True
  gather_facts: True
  tags: deploy
  roles:
    - app
