---
- hosts: localhost
  roles:
    - docker

- hosts:
  - sid.home
  - stretch.home
  remote_user: debian
  become: True
  gather_facts: False
  roles:
    - python
    - debian
    - locales
    - elasticsearch
    - git
    - vim
    - zsh

- hosts: sid.home
  remote_user: debian
  become: True
  gather_facts: False

  tasks:
    - name: Install ruby-dev
      apt:
        name: ruby-dev

    - name: Install solr-jetty
      apt:
        name: solr-jetty
