---
# app
app_path: /var/www/app
app_tmp_path: /tmp/app-deploy
app_repository: https://github.com/ngonzalez/music-rails.git
app_environment_path: "{{ app_path }}/.env"

# gcp
app_gcp_enabled: "{{ lookup('env', 'GCP_ENABLED') }}"

# google cloud sdk
google_cloud_sdk_keyring: "/usr/share/keyrings/cloud.google.gpg"
google_cloud_sdk_packages: "https://packages.cloud.google.com/apt"

# bundle
app_bundle_version: 2.2.29
app_bundle_src_path: /tmp/bundle
app_bundle_src_remote_path: bundle

# dragonfly
app_dragonfly_tmp_path: /tmp/dragonfly
app_dragonfly_remote_file_path: dragonfly.zip
app_dragonfly_local_file_path: /tmp/dragonfly.zip

# puma
app_puma_service_name: puma
app_puma_service_description: Puma is a simple, fast, threaded, and highly concurrent HTTP 1.1 server for Ruby/Rack applications.
app_puma_service_file: /etc/systemd/system/puma.service
app_puma_target_file: /etc/systemd/system/puma.target
app_puma_pid_path: /tmp/pids/server.pid
app_puma_service_file_sysv: /etc/init.d/puma
app_puma_sock: /tmp/puma.sock

# sidekiq
app_sidekiq_service_name: sidekiq
app_sidekiq_service_description: Simple, efficient background processing for Ruby.
app_sidekiq_service_file: /etc/systemd/system/sidekiq.service
app_sidekiq_target_file: /etc/systemd/system/sidekiq.target
app_sidekiq_pid_path: /tmp/pids/sidekiq.pid

# yarn
yarn_apt_key_url: https://dl.yarnpkg.com/debian/pubkey.gpg
yarn_repository_url: https://dl.yarnpkg.com/debian/

# nginx
nginx_port: 8000
nginx_user: www-data

# app server
app_server_host: 0.0.0.0
app_server_port: 80
app_server_path: /hls

# backup server
backup_server_host: 192.168.1.11
backup_server_port: 8080
backup_server_path: /Volumes/Samsung_T5

# postgresql
postgresql_host: 0.0.0.0
postgresql_port: 5432

# redis
redis_host: 0.0.0.0
redis_port: 6379
redis_db: 0