---
# app
app_path: /var/www/app
app_repository: https://github.com/ngonzalez/music-rails.git
app_config_path: "{{ app_path }}/config.sh"
app_environment_path: "{{ app_path }}/.env"

# app config
app_base_path: /Volumes/Untitled
app_hls_folder: /tmp/hls
app_hostname: link12.ddns.net

# gcp
app_gcp_config_path: "{{ app_path }}/gcp.json"
app_gcp_project_id: hebe-001
app_gcp_storage_bucket: hebe-001.appspot.com

# bundle
app_bundle_src_path: /home/{{ ansible_user }}/bundle
app_bundle_src_remote_path: cache/bundle

# pg dump
app_pg_dump_archive_path: /home/{{ ansible_user }}/backup.sql
app_pg_dump_archive_remote_path: cache/backup.sql

# puma
app_puma_service_name: puma
app_puma_service_description: Puma
app_puma_service_file: /etc/systemd/system/puma.service
app_puma_target_file: /etc/systemd/system/puma.target
app_puma_pid_path: /tmp/pids/server.pid

# sidekiq
app_sidekiq_service_name: sidekiq
app_sidekiq_service_description: Sidekiq
app_sidekiq_service_file: /etc/systemd/system/sidekiq.service
app_sidekiq_target_file: /etc/systemd/system/sidekiq.target
app_sidekiq_pid_path: /tmp/pids/sidekiq.pid
