---
# app
app_path: /var/www/app
app_tmp_path: /tmp/app-deploy
app_path_backend: "{{ app_path }}/backend"
app_tmp_path_backend: "{{ app_tmp_path }}/backend"
app_repository: https://github.com/ngonzalez/search-app.git

# gcp
app_gcp_enabled: "{{ lookup('env', 'GCP_ENABLED') }}"

# google cloud sdk
google_cloud_sdk_keyring: "/usr/share/keyrings/cloud.google.gpg"
google_cloud_sdk_packages: "https://packages.cloud.google.com/apt"

# bundle
app_bundle_version: 2.3.10
app_bundle_src_path: /tmp/bundle
app_bundle_src_remote_path: bundle

# puma
app_puma_service_name: puma
app_puma_service_description: Puma is a simple, fast, threaded, and highly concurrent HTTP 1.1 server for Ruby/Rack applications.
app_puma_service_file: /etc/systemd/system/puma.service
app_puma_target_file: /etc/systemd/system/puma.target
app_puma_pid_path: /tmp/pids/server.pid
app_puma_service_file_sysv: /etc/init.d/puma
app_puma_sock: /tmp/puma.sock
