---
- name: Update apt sources.list
  tags: apt
  shell: echo 'deb http://ftp.fr.debian.org/debian/ unstable main contrib non-free non-free-firmware' > /etc/apt/sources.list

# system dependencies
- name: Install packages that allow apt to be used over https
  tags: apt
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - gnupg
    - lsb-release

# developer
- name: Install developer packages
  tags: apt
  apt:
    name:
    - curl
    - dnsutils
    - iputils-ping
    - net-tools
    - htop
    - jq

# gpg
- name: Install gpg
  tags: apt
  apt:
    name:
      - gpg
      - gpg-agent

# sudo
- name: Install sudo
  tags: apt
  apt:
    name:
      - sudo
