---
- name: Update apt sources.list
  tags: apt
  shell: echo 'deb http://ftp.fr.debian.org/debian/ unstable main contrib non-free non-free-firmware' > /etc/apt/sources.list

# - name: Run the equivalent of "apt-get update" as a separate step
#   tags: apt
#   apt:
#     update_cache: yes

- name: Install packages that allow apt to be used over https
  tags: apt
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - gnupg
    - lsb-release

# apt dependencies
- name: Install system packages
  tags: apt
  apt:
    name:
    - curl
    - dnsutils
    - iputils-ping
    - net-tools
    - htop
    - jq

# gpg
- name: Install apt dependencies
  tags: apt
  apt:
    name:
      - gpg
      - gpg-agent
