---
- name: Remove motd
  file:
    path: /etc/motd
    state: absent

- name: Remove localtime
  file:
    path: /etc/localtime
    state: absent

- name: Set localtime to Europe/Paris
  file:
    src: /usr/share/zoneinfo/Europe/Paris
    dest: /etc/localtime
    owner: root
    group: root
    state: link
