---
# application dependencies
- name: Install application dependencies
  apt:
    name:
      - yarn

# app folder
- name: Remove application directory
  file:
    path: "{{ app_tmp_path }}"
    state: absent

- name: Create application tempoary directory
  file:
    path: "{{ app_tmp_path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

# git
- name: Clone application repository
  become_user: "{{ ansible_user }}"
  git:
    repo: "{{ app_repository }}"
    dest: "{{ app_tmp_path }}"

# dependencies
- name: yarn install
  become_user: "{{ ansible_user }}"
  command: yarn install
  args:
    chdir: "{{ app_tmp_path }}"

# link to application
- name: Create application directory
  file:
    path: /var/www
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Remove application directory
  file:
    path: "{{ app_path }}"
    state: absent

- name: Move to application folder
  command: mv -f "{{ app_tmp_path }}" "{{ app_path }}"
