---
- name: Install python3
  raw: test -e /usr/bin/python3 || apt install -yq python3
  changed_when: False
  no_log: True

- name: Install dependencies
  apt:
    name:
      - python3-apt
      - python3-psycopg2
  no_log: True
