# Container Runtime Interface
---
- name: Upgrade the OS (apt-get dist-upgrade)
  tags: crio
  apt:
    upgrade: dist

- name: Install apt dependencies
  tags: crio
  apt:
    name:
      - gpg
      - gpg-agent

- name: Add CRIO-O apt repository
  tags: crio
  shell: echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/ /"|sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
  environment:
    - OS: xUbuntu_22.04
    - CRIO_VERSION: 1.28


- name: Add CRIO-O apt repository
  tags: crio
  shell: echo "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$CRIO_VERSION/$OS/ /"|sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:$CRIO_VERSION.list
  environment:
    - OS: xUbuntu_22.04
    - CRIO_VERSION: 1.28

- name: Install CRI-O
  tags: crio
  apt:
    name:
    - cri-o
    - cri-o-runc

- name: Add cgroup config
  tags: crio
  template:
    src: cgroup-manager.conf.j2
    dest: /etc/crio/crio.conf.d/10-cgroup-manager.conf

- name: Add bridge configuration
  tags: crio
  template:
    src: cni.conf.j2
    dest: /etc/cni/net.d/100-cni.conf

- name: Start CRI-O
  tags: crio
  service:
    name: crio
    state: restarted
    daemon_reload: yes
