- name: Install zsh
  apt:
    name: zsh

- name: Configure zshrc
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - { src: zshrc, dest: "/root/.zshrc" }
    - { src: zshrc, dest: "/home/{{ ansible_user }}/.zshrc" }
