---
- name: Install ruby-dev
  apt:
    name: ruby-dev

- name: Install libpq-dev
  apt:
    name: libpq-dev

- name: Install python3-psycopg2
  apt:
    name:
      - python3-psycopg2

- name: Create postgresql database
  become_user: postgres
  community.general.postgresql_db:
    name: "{{ app_database }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0

- name: Create postgresql database user
  become_user: postgres
  community.general.postgresql_user:
    name: "{{ app_database_user }}"

- name: Remove application directory
  file:
    path: "{{ app_path }}"
    state: absent
  no_log: True

- name: Create application directory
  tags: deploy
  file:
    path: "{{ app_path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Include vault vars
  include_vars:
    file: vault.yml

- name: Copy ssh key id_rsa
  copy:
    content: "{{ debian_sid_id_rsa }}"
    dest: /home/{{ ansible_user}}/.ssh/id_host
    mode: 0600
    owner: "{{ ansible_user }}"

- name: Copy ssh key id_rsa_pub
  copy:
    content: "{{ debian_sid_id_rsa_pub }}"
    dest: /home/{{ ansible_user}}/.ssh/id_host.pub
    mode: 0644
    owner: "{{ ansible_user }}"

- name: Add new ssh key to ssh config
  lineinfile:
    line: " IdentityFile /home/{{ ansible_user }}/.ssh/id_host"
    dest: /home/{{ ansible_user }}/.ssh/config

- name: Clone application repository
  become_user: "{{ ansible_user }}"
  git:
    repo: "{{ app_repository }}"
    dest: "{{ app_path }}"

- name: Install application bundle dependencies
  apt:
    name:
      - build-essential
      - patch
      - zlib1g-dev
      - liblzma-dev
      - libtag1-dev

- name: Run application bundle
  become_user: "{{ ansible_user }}"
  command: /usr/bin/bundle2.7 install --path=vendor/cache
  args:
    chdir: "{{ app_path }}"
