---
- name: Add the hostname to /etc/hosts
  tags: etchosts
  lineinfile:
    dest: "/etc/hosts"
    line: "{{ apiserver_advertise_address }} {{ etchosts_hostname }} {{ node_name }}"
    state: present
    backup: true
