---
- name: Add link12.ddns.net to /etc/hosts file
  tags: etchosts
  lineinfile:
    dest: "/etc/hosts"
    line: "10.0.2.15 link12.ddns.net node-1"
    state: present
    backup: yes
  no_log: True
