---
- name: Install solr dependencies
  tags: solr
  apt:
    name:
      - acl
      - lsof
  no_log: True

- name: Get stats from solr file
  tags: solr
  stat:
    path: "{{ solr_local_path }}/{{ solr_folder_name }}.tgz"
  register: solr_tgz_file
  no_log: True

- name: Download solr
  tags: solr
  command: "wget -q {{ solr_download_url }}"
  args:
    chdir: "{{ solr_local_path }}"
  when: not solr_tgz_file.stat.exists
  no_log: True

- name: Get stats from solr path
  tags: solr
  stat:
    path: "{{ solr_local_path }}/{{ solr_folder_name }}"
  register: solr_local_src_path
  no_log: True

- name: Extract solr
  tags: solr
  command: "tar -zxf {{ solr_folder_name }}.tgz"
  args:
    chdir: "{{ solr_local_path }}"
  when: not solr_local_src_path.stat.exists
  no_log: True

- name: Create solr group
  tags: solr
  group:
    name: "{{ solr_user }}"
    state: present
  no_log: True

- name: Create solr user
  tags: solr
  user:
    name: "{{ solr_user }}"
    group: "{{ solr_user }}"
  no_log: True

- name: Set permissions on solr installation directory
  tags: solr
  file:
    dest: "{{ solr_folder_name }}"
    owner: "{{ solr_user }}"
    group: "{{ solr_user }}"
    recurse: yes
  no_log: True

- name: Get stats from solr bin path
  tags: solr
  stat:
    path: "{{ solr_opt_bin_path }}"
  register: solr_bin_path
  no_log: True

- name: Install solr
  tags: solr
  command: "./{{ solr_install_sh }} {{ solr_folder_name }}.tgz"
  args:
    chdir: "{{ solr_local_path }}"
  when: not solr_bin_path.stat.exists
  no_log: True

- name: Check solr core status
  tags: solr
  uri:
    url: http://{{ solr_host }}:{{ solr_port }}/solr/admin/cores?action=STATUS&core={{ solr_core }}
    method: GET
    return_content: yes
    status_code: 200
    body_format: json
  register: solr_core_http_response
  no_log: True

- name: Create solr core
  tags: solr
  become_user: "{{ solr_user }}"
  command: "./{{ solr_folder_name }}/bin/solr create -c {{ solr_core }} -p {{ solr_port }}"
  args:
    chdir: "{{ solr_local_path }}"
  when: "'index' not in solr_core_http_response.json.status.{{ solr_core }}"
  no_log: True
