---
- name: Install nginx
  tags: nginx
  apt:
    name: nginx
  no_log: True

- name: Configure nginx
  tags: nginx
  template:
    src: "nginx.conf.j2"
    dest: "{{ nginx_config_path }}"
    mode: 0644
  no_log: True

- name: Start nginx
  tags: nginx
  service:
    state: started
    name: nginx
    enabled: True
