---
- name: Install elasticsearch
  apt:
    name:
      - elasticsearch
  no_log: True

- name: Configure elasticsearch
  template:
    src: elasticsearch.yml.j2
    dest: "{{ elasticsearch_config_path }}"
    mode: 0644
  no_log: True

- name: Start elasticsearch
  systemd:
    daemon_reload: True
    state: started
    name: elasticsearch
  no_log: True
