---
- name: Install elasticsearch
  apt:
    name:
      - elasticsearch

- name: Configure elasticsearch
  template:
    src: elasticsearch.yml.j2
    dest: "{{ elasticsearch_config_path }}"
    mode: 0644

- name: Start elasticsearch
  systemd:
    daemon_reload: yes
    state: started
    name: elasticsearch
