---
- name: Install elasticsearch
  tags: elasticsearch
  apt:
    name:
      - elasticsearch
  no_log: True

- name: Configure elasticsearch
  tags: elasticsearch
  template:
    src: elasticsearch.yml.j2
    dest: "{{ elasticsearch_config_path }}"
    mode: 0644
  no_log: True

- name: Start elasticsearch
  tags: elasticsearch
  service:
    state: started
    name: elasticsearch
    enabled: True
