- name: Install openjdk-8-jdk
  apt:
    name: openjdk-8-jdk

- name: Install elastic dependencies
  apt:
    name:
      - wget
      - gnupg

- name: Add elastic.co apt key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Install apt-transport-https
  apt:
    name:
      - apt-transport-https

- name: Add elastic.co repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/{{ elasticsearch.version }}/apt stable main
    state: present
    update_cache: true

- name: Install elasticsearch
  when: is_elk_server is defined
  apt:
    name:
      - elasticsearch

- name: Configure elasticsearch
  when: is_elk_server is defined
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Install logstash
  when: is_elk_server is defined
  apt:
    name:
      - logstash

- name: Configure logstash
  when: is_elk_server is defined
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
  loop:
    - { src: logstash.conf.j2, dest: /etc/logstash/conf.d/logstash.conf }
    - { src: logstash_patterns, dest: "{{ logstash.path.patterns }}" }

- name: Install kibana
  when: is_elk_server is defined
  apt:
    name:
      - kibana

- name: Configure kibana
  when: is_elk_server is defined
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Install filebeat
  apt:
    name:
      - filebeat

- name: Configure filebeat
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Install rsyslog
  apt:
    name:
      - rsyslog

- name: Configure rsyslog
  command: echo "*.* @@{{ logstash.host if is_elk_server is defined else hostvars['stretch.home'].ipv4_address }}:{{ logstash.inputs.tcp }}" > {{ logstash.path.rsyslog }}

- name: systemd daemon_reload
  systemd:
    daemon_reload: yes

- name: systemd daemon_reexec
  systemd:
    daemon_reexec: yes

- name: Start elasticsearch
  when: is_elk_server is defined
  systemd:
    state: started
    name: elasticsearch

- name: Start logstash
  when: is_elk_server is defined
  systemd:
    state: started
    name: logstash

- name: Start kibana
  when: is_elk_server is defined
  systemd:
    state: started
    name: kibana

- name: Start filebeat
  systemd:
    state: started
    name: filebeat

- name: Start rsyslog
  systemd:
    state: started
    name: rsyslog
