---
- name: Create a debian-stretch container
  community.general.docker_container:
    name: docker-debian-stretch
    hostname: stretch.home
    image: debian-stretch:latest
    state: started
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - net_admin
      - sys_admin
    networks:
      - name: br0
        ipv4_address: "{{ hostvars['stretch.home'].ipv4_address }}"
    ports:
      - '2201:22'
      - '80:80'
      - '4000:4000'
      - '5044:5044'
    dns_search_domains:
      - home
    dns_servers:
      - 192.168.1.1

- name: Waiting for debian-stretch
  wait_for:
    host: "{{ hostvars['stretch.home'].ipv4_address }}"
    path: /etc/hosts

- name: Create a debian-sid container
  community.general.docker_container:
    name: docker-debian-sid
    hostname: sid.home
    image: debian-sid:latest
    state: started
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - net_admin
      - sys_admin
    networks:
      - name: br0
        ipv4_address: "{{ hostvars['sid.home'].ipv4_address }}"
    ports:
      - '2200:22'
    dns_search_domains:
      - home
    dns_servers:
      - 192.168.1.1

- name: Waiting for debian-sid
  wait_for:
    host: "{{ hostvars['sid.home'].ipv4_address }}"
    path: /etc/hosts
