# docker
---
- name: Install apt dependencies
  tags: docker
  apt:
    name:
      - gpg
      - gpg-agent

- name: Add docker apt key
  tags: docker
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor --yes -o /usr/share/keyrings/docker.gpg

- name: Add docker apt repository
  tags: docker
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Install docker
  tags: docker
  apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Add {{ ansible_user }} to docker group
  tags: docker
  user:
    name: "{{ ansible_user }}"
    group: docker

- name: Remove swapfile from /etc/fstab
  tags: docker
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  tags: docker
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Configure docker daemon
  tags: docker
  lineinfile:
    path: /etc/docker/daemon.json
    line: "{ \"exec-opts\": [\"native.cgroupdriver=systemd\"] }"
    create: yes

- name: Start docker
  tags: docker
  service:
    name: docker
    state: restarted
    daemon_reload: yes
