# docker
---
- name: Install apt dependencies
  apt:
    name:
      - gpg
      - gpg-agent

- name: Download docker gpg key
  tags: docker
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor --yes -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add docker apt repository
  tags: docker
  shell: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu jammy stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Install docker
  tags: docker
  apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    update_cache: yes

- name: Add vagrant user to docker group
  tags: docker
  user:
    name: vagrant
    group: docker

- name: Remove swapfile from /etc/fstab
  tags: docker
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  tags: docker
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Configure docker daemon
  tags: docker
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: 0644

- name: Start docker
  tags: docker
  service:
    name: docker
    state: restarted
    daemon_reload: yes
