---
- name: Create network br0
  community.general.docker_network:
    name: br0
    ipam_config:
      - subnet: "{{ docker_network_subnet }}"
        gateway: "{{ docker_network_gateway }}"
        iprange: "{{ docker_network_iprange }}"
  no_log: True

- name: Create a container from debian-stretch image
  community.general.docker_container:
    name: debian-stretch
    hostname: stretch.home
    image: ngonzalez121/debian-stretch-with-python:latest
    state: started
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - net_admin
      - sys_admin
    networks:
      - name: br0
        ipv4_address: "{{ hostvars['stretch.home'].ipv4_address }}"
    ports:
      - "{{ docker_stretch_external_ssh_port }}:22"
      - "{{ ansible_host }}:{{ docker_stretch_external_http_port }}:{{ nginx_port }}"
      - "{{ logstash_tcp_port }}:{{ logstash_tcp_port }}"
      - "{{ logstash_beats_port }}:{{ logstash_beats_port }}"
    dns_search_domains:
      - home
    dns_servers:
      - "{{ host_dns_server}}"
  no_log: True

- name: Waiting for container debian-stretch
  wait_for:
    host: "{{ hostvars['stretch.home'].ipv4_address }}"
    path: /etc/hosts
  no_log: True

- name: Create a container from debian-sid image
  community.general.docker_container:
    name: debian-sid
    hostname: sid.home
    image: ngonzalez121/debian-sid-with-python:latest
    state: started
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - net_admin
      - sys_admin
    networks:
      - name: br0
        ipv4_address: "{{ hostvars['sid.home'].ipv4_address }}"
    ports:
      - "{{ docker_sid_external_ssh_port }}:22"
      - "{{ ansible_host }}:{{ docker_sid_external_http_port }}:80"
      - "{{ ansible_host }}:{{ solr_port }}:{{ solr_port }}"
    dns_search_domains:
      - home
    dns_servers:
      - "{{ host_dns_server}}"
  no_log: True

- name: Waiting for container debian-sid
  wait_for:
    host: "{{ hostvars['sid.home'].ipv4_address }}"
    path: /etc/hosts
  no_log: True
