---
- name: Create docker network
  community.general.docker_network:
    name: "{{ docker_network_name }}"
    ipam_config:
      - subnet: "{{ docker_network_subnet }}"
        gateway: "{{ docker_network_gateway }}"
        iprange: "{{ docker_network_iprange }}"
  no_log: True

- name: Create docker container debian-stretch
  community.general.docker_container:
    name: debian-stretch
    hostname: "{{ docker_stretch_home_hostname }}"
    image: ngonzalez121/debian-stretch-with-python:latest
    state: started
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - net_admin
      - sys_admin
    networks:
      - name: "{{ docker_network_name }}"
        ipv4_address: "{{ hostvars[docker_stretch_home_hostname].ipv4_address }}"
    ports:
      - "{{ docker_stretch_home_ssh_port }}:{{ ssh_port }}"
      - "{{ ansible_host }}:{{ kibana_port }}:{{ nginx_port }}"
      - "{{ logstash_tcp_port }}:{{ logstash_tcp_port }}"
      - "{{ logstash_beats_port }}:{{ logstash_beats_port }}"
    dns_search_domains:
      - "{{ dns_server_search_domain }}"
    dns_servers:
      - "{{ dns_server_host }}"
  no_log: True

- name: Waiting for container debian-stretch
  wait_for:
    host: "{{ hostvars[docker_stretch_home_hostname].ipv4_address }}"
    path: /etc/hosts
  no_log: True

- name: Create container debian-sid
  community.general.docker_container:
    name: debian-sid
    hostname: "{{ docker_sid_home_hostname }}"
    image: ngonzalez121/debian-sid-with-python:latest
    state: started
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - net_admin
      - sys_admin
    networks:
      - name: "{{ docker_network_name }}"
        ipv4_address: "{{ hostvars[docker_sid_home_hostname].ipv4_address }}"
    ports:
      - "{{ docker_sid_home_ssh_port }}:{{ ssh_port }}"
      - "{{ ansible_host }}:{{ app_server_port }}:{{ nginx_port }}"
      - "{{ solr_port }}:{{ solr_port }}"
    dns_search_domains:
      - "{{ dns_server_search_domain }}"
    dns_servers:
      - "{{ dns_server_host }}"
  no_log: True

- name: Waiting for container debian-sid
  wait_for:
    host: "{{ hostvars[docker_sid_home_hostname].ipv4_address }}"
    path: /etc/hosts
  no_log: True
