---
- name: Install solr-jetty dependencies
  apt:
    name: openjdk-8-jdk
  no_log: True

- name: Install solr-jetty
  apt:
    name: solr-jetty
  no_log: True

- name: Start jetty9
  systemd:
    daemon_reload: True
    state: started
    name: jetty9
  no_log: True
