- name: Install vim
  apt:
    name: vim

- name: Configure vim
  template:
    src: vimrc
    dest: /etc/vim/vimrc.local
    mode: 0644

- name: Update vim defaults
  command: "echo 'GIT_EDITOR=vim' > /etc/profile.d/git.sh"
