- name: Install vim
  tags: vim
  apt:
    name: vim

- name: Configure vim
  tags: vim
  template:
    src: vimrc
    dest: /etc/vim/vimrc.local
    mode: "0644"

- name: Use vim as git's editor
  tags: vim
  copy:
    dest: /etc/profile.d/git.sh
    mode: "0644"
    content: |
      export GIT_EDITOR=vim
