# kubernetes
---
- name: Download kubernetes gpg key
  tags: kubernetes
  shell: curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor --yes -o /usr/share/keyrings/kubernetes-archive-keyring.gpg

- name: Add kubernetes apt repository
  tags: kubernetes
  shell: echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list > /dev/null

- name: Install Kubernetes binaries
  tags: kubernetes
  apt:
    name:
    - kubelet
    - kubeadm
    - kubectl

- name: Reset Kubernetes cluster
  tags: kubernetes
  command: kubeadm reset -f
  no_log: True

- name: Initialize the Kubernetes cluster
  tags: kubernetes
  command: kubeadm init --apiserver-advertise-address 192.168.56.10 \
                        --apiserver-cert-extra-sans 192.168.56.10 \
                        --pod-network-cidr 10.244.0.0/16 \
                        --node-name node-1

- name: Create .kube folder
  tags: kubernetes
  file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Copy file with owner and permissions
  tags: kubernetes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_user }}/.kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
    remote_src: yes

# By default, your cluster will not schedule Pods on the control-plane node for security reasons
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/
- name: Taint node
  tags: kubernetes
  command: kubectl taint nodes --all node-role.kubernetes.io/master-
  become: false

- name: Install the Tigera Calico operator and custom resource definitions
  tags: kubernetes
  command: kubectl create -f https://docs.projectcalico.org/master/manifests/tigera-operator.yaml
  become: false

- name: Install Calico by creating the necessary custom resource
  tags: kubernetes
  command: kubectl create -f https://gist.githubusercontent.com/ngonzalez/2982b3115ed14982318088cf4cc8a415/raw/02f882a2a5570af59dcc36ebc512f2727537b1a3/custom-resources.yaml
  become: false

- name: Create kube flannel run directory
  tags: kubernetes
  file:
    path: /run/flannel
    state: directory
    mode: 0755

- name: Add subnet.env
  tags: kubernetes
  template:
    src: subnet.env.j2
    dest: /run/flannel/subnet.env

- name: Apply kube flannel
  tags: kubernetes
  command: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
  become: false
