# Kubernetes
---
- name: Add an apt signing key for Kubernetes
  tags: kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adding apt repository for Kubernetes
  tags: kubernetes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

- name: Install Kubernetes binaries
  tags: kubernetes
  apt:
    name:
    - kubelet
    - kubeadm
    - kubectl

- name: Reset Kubernetes cluster
  tags: kubernetes
  command: kubeadm reset -f --cri-socket {{ cri_socket }}

- name: Pull images
  tags: kubernetes
  command: kubeadm config images pull --cri-socket {{ cri_socket }}

- name: Initialize the Kubernetes cluster
  tags: kubernetes
  command: kubeadm init --apiserver-advertise-address {{ apiserver_advertise_address }} \
                        --apiserver-cert-extra-sans {{ apiserver_advertise_address }} \
                        --cri-socket {{ cri_socket }} \
                        --pod-network-cidr {{ pod_network_cidr }} \
                        --node-name {{ node_name }}

- name: Create .kube folder
  tags: kubernetes
  file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Copy file with owner and permissions
  tags: kubernetes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_user }}/.kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0400
    remote_src: True

- name: Taint node as control plane
  tags: kubernetes
  become_user: "{{ ansible_user }}"
  command: kubectl taint nodes --all node-role.kubernetes.io/control-plane-

# helm
#- name: Install Helm
#  tags: kubernetes
#  command: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

# tigera-operator
- name: Add Calico Repository
  tags: kubernetes
  become_user: "{{ ansible_user }}"
  command: helm repo add projectcalico https://projectcalico.docs.tigera.io/charts

- name: Create Tigera Operator Namespace
  tags: kubernetes
  become_user: "{{ ansible_user }}"
  command: kubectl create ns tigera-operator

- name: Install Tigera Operator
  tags: kubernetes
  become_user: "{{ ansible_user }}"
  command: helm upgrade --install calico projectcalico/tigera-operator --namespace tigera-operator

# calico
- name: Install Calico CNI
  tags: kubernetes
  become_user: "{{ ansible_user }}"
  command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/master/manifests/calico.yaml

- name: Install Calico Custom Resources
  tags: kubernetes
  become_user: "{{ ansible_user }}"
  command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/master/manifests/custom-resources.yaml
