# kubernetes
---
- name: Upgrade the OS (apt-get dist-upgrade)
  tags: kubernetes
  apt:
    upgrade: dist

# Container Runtime Interface
- name: Install apt dependencies
  tags: kubernetes
  apt:
    name:
      - gpg
      - gpg-agent

- name: Download CRIO-O gpg key
  tags: kubernetes
  shell: curl -fsSL https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/Release.key | gpg --dearmor --yes -o /usr/share/keyrings/libcontainers-archive-keyring.gpg
  environment:
    - OS: xUbuntu_22.04

- name: Add CRIO-O apt repository
  tags: kubernetes
  shell: echo "deb [signed-by=/usr/share/keyrings/libcontainers-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
  environment:
    - OS: xUbuntu_22.04

- name: Download CRIO-O gpg key
  tags: kubernetes
  shell: curl -fsSL https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/Release.key | gpg --dearmor --yes -o /usr/share/keyrings/libcontainers-crio-archive-keyring.gpg
  environment:
    - OS: xUbuntu_22.04
    - VERSION: 1.25

- name: Add CRIO-O apt repository
  tags: kubernetes
  shell: echo "deb [signed-by=/usr/share/keyrings/libcontainers-crio-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:$VERSION.list
  environment:
    - OS: xUbuntu_22.04
    - VERSION: 1.25

- name: Run the equivalent of "apt-get update" as a separate step
  tags: kubernetes
  apt:
    update_cache: yes

- name: Install CRI-O
  tags: kubernetes
  apt:
    name:
    - cri-o
    - cri-o-runc

- name: Add cgroup config
  tags: kubernetes
  template:
    src: cgroup-manager.conf.j2
    dest: /etc/crio/crio.conf.d/10-cgroup-manager.conf

- name: Start CRI-O
  tags: kubernetes
  service:
    name: crio
    state: restarted
    daemon_reload: yes

# Kubernetes
- name: Add an apt signing key for Kubernetes
  tags: kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adding apt repository for Kubernetes
  tags: kubernetes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

- name: Install Kubernetes binaries
  tags: kubernetes
  apt:
    name:
    - kubelet
    - kubeadm
    - kubectl

- name: Reset Kubernetes cluster
  tags: kubernetes
  command: kubeadm reset -f --cri-socket {{ cri_socket }}

- name: Pull images
  tags: kubernetes
  command: kubeadm config images pull --cri-socket {{ cri_socket }}

- name: Initialize the Kubernetes cluster
  tags: kubernetes
  command: kubeadm init --apiserver-advertise-address {{ apiserver_advertise_address }} \
                        --apiserver-cert-extra-sans {{ apiserver_advertise_address }} \
                        --cri-socket {{ cri_socket }} \
                        --pod-network-cidr {{ pod_network_cidr }} \
                        --node-name {{ node_name }}

- name: Create .kube folder
  tags: kubernetes
  file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Copy file with owner and permissions
  tags: kubernetes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_user }}/.kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
    remote_src: True

# deprecated
# - name: Taint node as master
#   tags: kubernetes
#   command: kubectl taint nodes --all node-role.kubernetes.io/master-
#   become: false

- name: Taint node as control plane
  tags: kubernetes
  command: kubectl taint nodes --all node-role.kubernetes.io/control-plane-
  become: false

# calico
- name: Install Tigera Operator
  tags: kubernetes
  command: kubectl create -f https://docs.projectcalico.org/master/manifests/tigera-operator.yaml
  become: false

- name: Install Calico Custom Resources
  tags: kubernetes
  command: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/master/manifests/custom-resources.yaml
  become: false

- name: Install Calico CNI
  tags: kubernetes
  command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/master/manifests/calico.yaml
  become: false

# dns
- name: Set kube-dns service external IP
  tags: admin
  become_user: "{{ ansible_user }}"
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl -n kube-system patch svc kube-dns -p '{"spec":{"externalIPs":["{{ apiserver_advertise_address }}"]}}'

- name: Add config for coredns
  tags: admin
  become_user: "{{ ansible_user }}"
  shell:
    chdir: "{{ admin_path }}"
    cmd: kubectl apply -f configmap/coredns.yaml

# # kubernetes-dashboard
# - name: Add kubernetes-dashboard
#   tags: kubernetes
#   command: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml
#   become: false
# 
# - name: Set kubernetes-dashboard service external IP
#   tags: kubernetes
#   command: kubectl -n kubernetes-dashboard patch svc kubernetes-dashboard -p '{"spec":{"externalIPs":["{{ apiserver_advertise_address }}"]}}'
#   become: false
# 
# # kubernetes-dashboard service-account
# - name: Setup Service Account Admin User
#   tags: admin
#   become_user: "{{ ansible_user }}"
#   shell:
#     chdir: "{{ admin_path }}"
#     cmd: kubectl apply -f service-account/admin-user.yaml
# 
# - name: Setup Service Account Cluster Admin
#   tags: admin
#   become_user: "{{ ansible_user }}"
#   shell:
#     chdir: "{{ admin_path }}"
#     cmd: kubectl apply -f service-account/cluster-admin.yaml
# 
# - name: Generate Service Account Token
#   tags: admin
#   become_user: "{{ ansible_user }}"
#   shell:
#     chdir: "{{ admin_path }}"
#     cmd: kubectl -n kubernetes-dashboard create token admin-user
